<a href="https://colab.research.google.com/github/MarisolHernandezJim/Unidad1/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy es una libreria de Python.
NumPy se utiliza para trabajar matrices o arreglos.
NumPy es la abreviatura de "puthon numerico".
Tambien tiene funciones para trabajar en el dominio del algebra lineal, la transformada y las matrices.
En Python tenemos listas que sirven como matrices, pero son lentas de procesar.
NumPy tiene como objetivo proporcionar un objetivo de matriz que sea 50 veces mas rapido que las listas tradicionales.

In [1]:
#tenemos que importas la libreria
import numpy

arreglo = numpy.array([1,2,3,4,5,])
print(arreglo)

[1 2 3 4 5]


NumPy cono np.
Numpy generalmente se importa bajo el alias np.
En Python los alias son un nombre alternativo para referirse a la misma cosa.


In [3]:
import numpy as np
arreglo = np.array([6,7,8,9,10])
print(arreglo)

[ 6  7  8  9 10]


Comprobando la version de NumPy
La cadena der la version se almacena en el atributo __version__

In [4]:
import numpy as np
print(np.__version__)


2.0.2


NumPy creando matrices crear un objeto ndarray de Numpy.
NumPy se utiliza para trabajar con matrices.
El objetivo de matriz se llama ndrray.
Podemos crear un NumPy ndarray utilizando la funcion array()

In [7]:
import numpy as np
arreglo = np.array(["Raul", "Ana","Kimberly","Yazmin"])
print(arreglo)
print(type(arreglo))

['Raul' 'Ana' 'Kimberly' 'Yazmin']
<class 'numpy.ndarray'>


Dimensiones en matrices.
Una dimension en matrices es un nivel de profundidad de matriz (matrices anidadas).
Una matriz anidada contienen matrices como elementos.
Matrices 0-D. Son elementos de una matriz. Cada valor de una matriz es una matriz 0.D . Ejemplo: Crea una matriz 0-D con un valor de 42.

In [8]:
import numpy as np
arreglo = np.array(42)
print(arreglo)



42


Matrices 1-D.
Una matriz que tiene matrices 0-D como elementos se denomina matriz unidimensional o 1-D
Estan son las matrices mas comunes y basicas.
Ejemplo: Crea  una matriz de una dimension que tenga los valores 1,2,3,4,5

In [9]:
import numpy as np
arreglo = np.array([1,2,3,4,5])
print(arreglo)

[1 2 3 4 5]


Matrices 2D.
Una matriz que tiene matrices de una dimension como elementos se denomina matrice 2D.
A menudo se untilizan para representar matrices de segundo orden.
NumPy tiene un submodulo completo dedicado a observaciones con matrices llamada numpy.mat
Ejemplo: crea una matriz de 2D que contenga 2 matrices con los valores 123 y 456.

In [11]:
import numpy as np
arreglo = np.array([[1,2,3],[4,5,6]])
print(arreglo)

[[1 2 3]
 [4 5 6]]


matrices 3D
Una matriz que tienes matrices 2D se denomina matriz 3D.
estas matrices se utilizan para representar una matriz de tercer orden.
Ejemplo: crea una matriz 3D con dos matrices bidimensionales, amabas conteniendo dos matrices con los valores 123 y 456.

In [12]:
import numpy as np
arreglo = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arreglo)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
