<a href="https://colab.research.google.com/github/MarisolHernandezJim/Unidad1/blob/main/practica6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

  Marisol Hernandez-24/09/20205
  Practica 6-Cortar arreglos NumPy

-----------------------------------------------
Slice en python significa tomar elementos de un indice determinado a otro determinado indice.
pasamos slice en lugar del indice de esta manera:[start:end]
sino pasamos el inicio se considera 0.
Sino pasamos el final su longitud es considerada una matriz de una dimension


---
ejemplo:([1,2,3,4,5,6,7])

cortar los elementos de indice 1 a indice 5




In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


ejemplo 2
([1,2,3,4,5,6,7])
cortar indice 4 hasta el final de la matriz

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


ejemplo 3
([1,2,3,4,5,6,7])
cortar elementos desde el principio hasta el indice 5

In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:5])

[1 2 3 4 5]


ejemplo 4
([1,2,3,4,5,6,7])
corte negativo utilizamos el operador - para hacer referencia a un indice desde el final cortar del indice 3 desde el final al 1

In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])


[5 6]
